---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
  labels:
    provider: "fabric8"
    project: "hl7test"
    version: "1.0-SNAPSHOT"
    group: "com.redhat.demo"
  name: "hl7test-service"
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    project: "hl7test"
    provider: "fabric8"
    group: "com.redhat.demo"
