---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/camel.svg"
    labels:
      provider: "fabric8"
      project: "hl7test"
      version: "1.0-SNAPSHOT"
      group: "com.redhat.demo"
    name: "hl7test"
  spec:
    ports:
    - name: "default"
      port: 8888
      protocol: "TCP"
      targetPort: 8888
    selector:
      project: "hl7test"
      provider: "fabric8"
      group: "com.redhat.demo"
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/camel.svg"
      fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=hl7test&var-version=1.0-SNAPSHOT"
    labels:
      provider: "fabric8"
      project: "hl7test"
      version: "1.0-SNAPSHOT"
      group: "com.redhat.demo"
    name: "hl7test"
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: "hl7test"
        provider: "fabric8"
        group: "com.redhat.demo"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/camel.svg"
          fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=hl7test&var-version=1.0-SNAPSHOT"
        labels:
          provider: "fabric8"
          project: "hl7test"
          version: "1.0-SNAPSHOT"
          group: "com.redhat.demo"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: "JAVA_APP_DIR"
            value: "/deployments"
          image: "hl7test:latest"
          imagePullPolicy: "Always"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 180
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 9779
            name: "prometheus"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
